export interface EmailTemplateData {
  ticketNumber: string;
  title: string;
  priority: string;
  category: string;
  requester: string;
  status?: string;
  assignedAgent?: string;
  resolution?: string;
  ticketUrl: string;
}

export function buildEmailTemplate(
  heading: string,
  message: string,
  data: EmailTemplateData
): string {
  return `
  <!DOCTYPE html>
  <html>
    <body style="font-family: Arial, sans-serif; background:#f5f5f5; padding:20px;">
      <div style="max-width:700px;margin:auto;background:#ffffff;border-radius:8px;padding:24px;">

        <h2 style="color:#274C5A;margin-bottom:8px;">
          Lazem IT Ticketing
        </h2>

        <h3>${heading}</h3>

        <p>${message}</p>

        <table style="width:100%;border-collapse:collapse;margin-top:20px;">
          <tr>
            <td><strong>Ticket #</strong></td>
            <td>${data.ticketNumber}</td>
          </tr>

          <tr>
            <td><strong>Title</strong></td>
            <td>${data.title}</td>
          </tr>

          <tr>
            <td><strong>Priority</strong></td>
            <td>${data.priority}</td>
          </tr>

          <tr>
            <td><strong>Category</strong></td>
            <td>${data.category}</td>
          </tr>

          <tr>
            <td><strong>Requester</strong></td>
            <td>${data.requester}</td>
          </tr>

          ${
            data.status
              ? `
          <tr>
            <td><strong>Status</strong></td>
            <td>${data.status}</td>
          </tr>`
              : ""
          }

          ${
            data.assignedAgent
              ? `
          <tr>
            <td><strong>Assigned Agent</strong></td>
            <td>${data.assignedAgent}</td>
          </tr>`
              : ""
          }

          ${
            data.resolution
              ? `
          <tr>
            <td><strong>Resolution</strong></td>
            <td>${data.resolution}</td>
          </tr>`
              : ""
          }

        </table>

        <div style="margin-top:30px;">
          <a
            href="${data.ticketUrl}"
            style="
              background:#274C5A;
              color:white;
              padding:12px 20px;
              text-decoration:none;
              border-radius:6px;
            "
          >
            Open Ticket
          </a>
        </div>

        <hr style="margin-top:40px;" />

        <small>
          This email was automatically generated by Lazem IT Ticketing System.
        </small>

      </div>
    </body>
  </html>
  `;
}
